api:
  dashboard: true
  
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
    
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  http:
    acme:
      email: myemail@mondomaine.com
      storage: acme.json
      # Dev
      caServer: "https://acme-staging.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: http

